require:
  - rubocop/cop/internal_affairs
  - rubocop-rspec
AllCops:
  Exclude:
    - 'coverage/**/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'lib/scim-kit.rb'

RSpec/NamedSubject:
  Enabled: false
